// build-sprite.ts
import fs from "fs-extra";
import path from "path";
import fg from "fast-glob";
import chokidar from "chokidar";
import Sprite from "svg-sprite";

// --- Default config ---
let inputDir = "./public/assets/svg";
let outputSprite = "./public/assets/icons.svg";
let outputEnum = "./constants/IconName.ts";
let watchMode = false;

// --- Parse CLI flags ---
process.argv.forEach((arg) => {
  if (arg === "--watch" || arg === "-w") watchMode = true;
  if (arg.startsWith("--input=")) inputDir = arg.split("=")[1];
  if (arg.startsWith("--sprite=")) outputSprite = arg.split("=")[1];
  if (arg.startsWith("--enum=")) outputEnum = arg.split("=")[1];
});

// --- Helpers ---
function toEnumKey(filePath: string) {
  const baseName = path.basename(filePath, ".svg")
    .replace(/[^a-zA-Z0-9]/g, "_"); // normalize ALL non-alphanumeric chars to underscores

  return baseName
    .split(/_+/) // split on one or more underscores
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}





// --- Build function ---
async function buildSprite() {
  await fs.ensureDir(path.dirname(outputSprite));
  await fs.ensureDir(path.dirname(outputEnum));

  const files = await fg([`${inputDir.replace(/\\/g, "/")}/**/*.svg`], {
    absolute: true,
  });

  const config = {
    mode: {
      symbol: {
        dest: ".", // output directory
        sprite: path.basename(outputSprite),
      },
    },
    shape: {
      id: {
        generator: (filePath: string) =>
          path.basename(filePath, ".svg")
            .toLowerCase()
            .replace(/-/g, "_")              // convert hyphens to underscores
            .replace(/[^a-z0-9_]+/g, "_")    // normalize
            .replace(/_+/g, "_"),            // collapse multiple underscores
      },
    },
  }
 

  const sprite = new Sprite(config);
  const enumEntries: string[] = [];

  for (const file of files) {
    const svgText = await fs.readFile(file, "utf8");
    sprite.add(file, null, svgText);
    enumEntries.push(`  ${toEnumKey(file)} = "${config.shape.id.generator(file)}",`);
  }

  sprite.compile(async (error, result) => {
    if (error) throw error;

    const symbolSprite = result.symbol.sprite.contents.toString();
    await fs.writeFile(outputSprite, symbolSprite);

    await fs.writeFile(
      outputEnum,
      `// Auto-generated by build-sprite.ts\nexport enum IconName {\n${enumEntries.join(
        "\n"
      )}\n}\n\nexport type IconNameType = keyof typeof IconName;\n`
    );

    console.log(`✅ Sprite built: ${outputSprite}`);
    console.log(`✅ Enum built: ${outputEnum}`);
  });
}

// --- Main flow ---
async function main() {
  await buildSprite();

  if (watchMode) {
    console.log(`👀 Watching ${inputDir} for SVG changes...`);
    const watcher = chokidar.watch(`${inputDir.replace(/\\/g, "/")}/**/*.svg`);
    watcher.on("add", buildSprite);
    watcher.on("change", buildSprite);
    watcher.on("unlink", buildSprite);

    process.on("SIGINT", () => {
      console.log("🛑 Exiting watcher...");
      watcher.close();
      process.exit(0);
    });
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
